### ISSUE TITLE
Shiftキーを押すことで素材一個ずつではなく、一気に作成できる機能

### ISSUE THREAD

**Issue by kinoko2k** [Sakaki-Aruka/custom-crafter#169]
普通の作業台では、Shiftを長押し時に作成すると、素材が足りる場合複数アイテムが作成できます。
一個ずつ押してもいいとは思いますが、作業の効率化やアイテムを多量に作成する場合は、Shiftが使えるといいと思います。

**Comment by Sakaki-Aruka** [comment]
取り込んでみます。
